### PR TITLE
Structure Python package

### PR DESCRIPTION
**Pull request by pylipp**
With this PR, the project structure is adjusted to the conventional Python-package structure. The functional package code is contained in `boxwise_flask`, and can be imported from that namespace.

This allows to set up the first test! I'm using [pytest](https://docs.pytest.org/en/latest/) because I like its handling a lot. Test programs are very clear with little boilerplate code; same goes for test fixtures. Output of failed tests is very informative. Try it :) `pytest` from the project root.

@HaGuesto @aerinsol Do we need an ADR for using pytest?

### CODE REVIEW

**Comment by pylipp** [comment]
Since during mid-sprint discussion no further objections were raised, I'll merge this soon @HaGuesto

**Comment by aerinsol** [comment]
@pylipp I think it would be interesting to cover pytest, flake8, Black and anything else in ADR in terms of full Flask and Python testing library

**Comment by pylipp** [comment]
@aerinsol you mean a single ADR for justifying the flask/Python tools/libraries? Should that be part of the present PR?

**Comment by aerinsol** [comment]
Yeah, that's what I mean. Sure, why not put it in the PR :)

**Pull request merged**
