### PR TITLE
Create graphql-ariadne-apollo.md

### PR DESCRIPTION
**Pull request by aerinsol**
First draft not yet complete

### CODE REVIEW

**Comment by aerinsol** [comment]
Oops, forgot to add context.

**Comment by mcgnly** [comment]
@aerinsol is this still in progress, or ready to review?

**Comment by aerinsol** [comment]
@DurkoMatko I didn't tag you on this for review, but probably should have given you had some questions about why we were using a GraphQL single endpoint approach instead of REST. Take a look and let me know if you have questions.

**Comment by DurkoMatko** [comment]
@aerinsol thx for tagging me, it was an interesting read, makes more sense now.. btw _"Ariadne was selected over Graphene on the client side due to"_ should be _"server side"_ but I guess it aint important :)

**Comment by DurkoMatko** [comment]
@aerinsol thx for tagging me, it was an interesting read, makes more sense now.. btw "Ariadne was selected over Graphene on the client side due to" should be "server side" but I guess it aint important

**Comment by aerinsol** [comment]
@DurkoMatko thanks! Fixed the typos

**Pull request merged**
