### PR TITLE
demo of ariadne and demo of peewee

### PR DESCRIPTION
**Pull request by mcgnly**
one query all the way through 🎉

### CODE REVIEW

**Comment by pylipp** [comment]
The `/api/somequery/` endpoint now works

**Comment by mcgnly** [comment]
the allCamps query is also hooked up now to gql and viewable on the playground!

**Comment by mcgnly** [comment]
[Create resolvers for GraphQL and database #xtra-large #python #graphql](https://trello.com/c/s3PK59Tw/519-create-resolvers-for-graphql-and-database-xtra-large-python-graphql)

**Comment by HaGuesto** [comment]
I merged #7
I pushed a commit to resolve the issues I created.

**Comment by HaGuesto** [comment]
I will merge it now since my `feature/add-circleci` branch heavily depends on it.

**Comment by pylipp** [comment]
[Set up Ariadne as GraphQL server in Staging #flask #python #medium](https://trello.com/c/Nzq0h0z5/517-set-up-ariadne-as-graphql-server-in-staging-flask-python-medium)

**Pull request merged**
