### PR TITLE
Enable flask debug mode

### PR DESCRIPTION
**Pull request by pylipp**
- hot-reloading of the flask app is now possible: When the app is already up and running, changes in the source code will be detected.
- debugging is possible by using the built-in debugger. For trying out, add a `raise Exception` at the beginning of the `/`-route, and direct your browser to `http://0.0.0.0:5000`. You can attach a console by clicking the icons on the right of the traceback lines. I tried to run `pdb` but flask did not seem to like it.
- cleaned up the flask Dockerfile a little

### CODE REVIEW

**Comment by pylipp** [comment]
[Fixing flask dev environment to make proper debugging and hot reload possible #large](https://trello.com/c/bzq9sZS8/542-fixing-flask-dev-environment-to-make-proper-debugging-and-hot-reload-possible-large)

**Comment by pylipp** [comment]
> I assume you'll have some way to remember to remove the development env when you're ready to launch the prod version of this?

@jdcsgh You're absolutely right. I don't know our deployment routine; I think we should configure the setting there.

**Comment by mcgnly** [comment]
I would suspect it's either a different dockerfile or an env variable that
the ci holds?

**Comment by HaGuesto** [comment]
The dockerfile is only needed for the local development environment. On the production environment of the GAE Docker is not used.
Therefore, I can approve the PR and will merge it.

**Comment by mcgnly** [comment]
@HaGuesto maybe you can show me around the GAE setup someday, I'm not familiar with it at all :)

**Pull request merged**
